# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 08:13
from __future__ import unicode_literals

import django.core.serializers.json
from django.db import migrations, models
import django_pgjsonb.fields
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20, null=True)),
                ('DataSequence', django_pgjsonb.fields.JSONField(decode_kwargs={}, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HBT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HBT_ID', models.IntegerField(null=True)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Tail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.TextField(null=True)),
                ('Accuracy', models.FloatField(null=True)),
            ],
        ),
    ]
